/*
 * Copyright (c) 2017 Linaro
 * SPDX-License-Identifier: Apache-2.0
 */

#ifdef CONFIG_SOC_SERIES_UWP566X
#define FLASH_AREA_IMAGE_SECTOR_SIZE	0x010000
#define FLASH_DEV_NAME		FLASH_LABEL

/* partition@10000 */
#define FLASH_AREA_IMAGE_0_OFFSET   FLASH_AREA_IMAGE_0_OFFSET_0
#define FLASH_AREA_IMAGE_0_SIZE     FLASH_AREA_IMAGE_0_SIZE_0

/* partition@56000 */
#define FLASH_AREA_IMAGE_1_OFFSET   FLASH_AREA_IMAGE_1_OFFSET_0
#define FLASH_AREA_IMAGE_1_SIZE     FLASH_AREA_IMAGE_1_SIZE_0

/* partition@9c000 */
#define FLASH_AREA_IMAGE_SCRATCH_OFFSET     FLASH_AREA_IMAGE_SCRATCH_OFFSET_0
#define FLASH_AREA_IMAGE_SCRATCH_SIZE       FLASH_AREA_IMAGE_SCRATCH_SIZE_0


#endif
